security:
    enable_authenticator_manager: true
    password_hashers:
        App\Entity\User:
            algorithm: auto
        
        App\Entity\Admin:
            algorithm: auto

        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: auto
            cost: 15

    providers:
        admin_provider:
            entity:
                class: App\Entity\Admin
                property: email

        app_user_provider:
            entity:
                class: App\Entity\User
                property: email


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern : ^/api/
            stateless: true
            provider: app_user_provider
            json_login:
                check_path: /api/login  
                username_path: email  
                password_path: password 
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            jwt: ~
        admin:
            pattern: ^/admin
            lazy: true
            provider: admin_provider
            form_login:
                login_path: /admin/login
                check_path: admin_login
                default_target_path: /admin
            logout:
                path: /admin/logout
                target: /
            access_denied_url: /access-denied
            security: true

        main:
            user_checker: App\Service\UserChecker
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: /login
                check_path: app_login
                default_target_path: /cars
            logout:
                path: /logout
                target: /
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path: /
                httponly: true
            access_denied_url: /access-denied
            security: true

    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/users/\d+/cars$, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/doc$, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/admin/login, roles: PUBLIC_ACCESS }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/users/\d+/verify/, roles: PUBLIC_ACCESS }
        - { path: ^/registration_verified, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/cars/, roles: ROLE_VERIFIED }
        - { path: ^/car/\d+/appointment, roles: ROLE_USER }
        - { path: ^/api/appointments, roles: ROLE_USER }
        - { path: ^/cars$, roles: ROLE_USER }