version: '3.8'

services:
  # Database service
  database:
    image: mysql:8.0 # Use MySQL image (adjust version if needed)
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-projekat3_db} # Your database name
      MYSQL_USER: ${MYSQL_USER:-root} # Database user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-1236} # Database user password
    ports:
      - "3306:3306"  # Expose MySQL port
    volumes:
      - database_data:/var/lib/mysql:rw  # Persist database data

volumes:
  database_data:
    driver: local