
api_doc:
    path: /api/doc
    controller: nelmio_api_doc.controller.swagger_ui

app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }
