parameters:
    profile_pictures_directory: '%kernel.project_dir%/%env(PROFILE_PICTURES_DIRECTORY)%'
    registration_base_cost: '%env(resolve:REGISTRATION_BASE_COST)%'
    discount_code: '%env(DISCOUNT_CODE)%' 
    api_host: '%env(API_HOST)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\RegistrationCostService:
        arguments:
            $registrationBaseCost: '%registration_base_cost%'  
            $discountCode: '%discount_code%'  

    App\Resolver\CarValueResolver:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            
    App\Controller\CarController:
        arguments:
            $apiHost: '%env(string:API_HOST)%'


