parameters:
    profile_pictures_directory: '%kernel.project_dir%/%env(PROFILE_PICTURES_DIRECTORY)%'
    registration_base_cost: '%env(REGISTRATION_BASE_COST)%'
    discount_code: '%env(DISCOUNT_CODE)%' 
    api_host: '%env(API_HOST)%'
    app_host: '%env(APP_HOST)%'

services:
    _defaults:
        autowire: true     
        autoconfigure: true 

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\RegistrationCostService:
        arguments:
            $registrationBaseCost: '%registration_base_cost%'  
            $discountCode: '%discount_code%'  

    App\Resolver\CarValueResolver:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
        tags:
            - { name: 'controller.argument_value_resolver', priority: 10 }

    App\Resolver\UserValueResolver:
        arguments:
            $userRepository: '@App\Repository\UserRepository'
        tags:
            - { name: 'controller.argument_value_resolver', priority: 10 }

    
    App\Controller\CarController:
        arguments:
            $apiHost: '%api_host%' 

    App\Service\CarService:
        arguments:
            $apiHost: '%api_host%' 
    
    App\Controller\ResetPasswordController:
        arguments:
            $appHost: '%app_host%'
    
    App\Service\RegistrationService:
        arguments:
            $appHost: '%app_host%'
    
    App\Service\SchedulingService:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            
    App\Command\CarsExpiringRegistrationCommand: 
        tags:
            - { name: 'console.command', command: 'app:cars-expiring-registration' }
